<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Kahve uygulaması.aspx.cs" Inherits="KahveSitesi.Kahve_uygulaması" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .autp-style1 {
            height: 78px;
            width: 695px;
        }
        .auto-style1 {
            height: 78px;
            width: 695px;
            font-size: x-small;
        }
        .auto-style2 {
            width: 698px;
            height: 700px;
        }
        .auto-style3 {
            margin-left: 0px;
        }
        .auto-style4 {
            font-size: x-large;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div style="width:698px; margin-left:300px; height:150px;">
            
            <asp:Image ID="Image1" runat="server" Height="150px" Width="698" ImageUrl="~/image/coffe.jpg" />
            <div>
                &nbsp;</div>
            <div style="height:80px; width:698px; background-color:aquamarine">
                <table class="auto-style1">
                    <tr>
                        <td>
                            <h2>ANASAYFA</h2>
                        </td>
                        <td>
                            <h2>KAHVE ÜZERİNE</h2>
                        </td>
                        <td>
                            <h2>HAKKIMIZDA</h2>
                        </td>
                        <td>
                            <h2>İLTEŞİŞİM</h2>
                        </td>
                    </tr>
                </table>
            </div>
            <div style="width:698px;">&nbsp;</div>
            <div style="background-color:coral" class="auto-style2">
                <div>
                    <div class="v-stack gap-4.5" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; grid-template-columns: minmax(0px, 1fr); align-content: start; display: grid; gap: 1.125rem; color: rgb(17, 17, 17); font-family: &quot;Nunito Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <h1 class="h1" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin: 0px; font-family: var(--heading-font-family); font-weight: var(--heading-font-weight); font-style: var(--heading-font-style); letter-spacing: var(--heading-letter-spacing); text-transform: var(--heading-text-transform); overflow-wrap: anywhere; font-size: var(--text-h1); line-height: 1.3;">KAHVE NEDİR, NASIL ÜRETİLİR? KAHVEYE DAİR A&#39;DAN Z&#39;YE HER ŞEY!</h1>
                    </div>
                    <div class="prose" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; overflow-wrap: anywhere; color: rgb(17, 17, 17); font-family: &quot;Nunito Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <p class="p1" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin: 0px; margin-block-start: 0px !important;">
                            <span class="s1" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin-block-start: 0px !important;">Kahve, coffea isimli ağacın meyvelerinden&nbsp; çeşitli işlemler sonucu&nbsp; çekirdeklerinin ayrılması ve bölgeden bölgeye farklılık gösteren demleme şekilleriyle hazırlanmasıyla elde edilen içecek türüdür. Bu meyvelerin çekirdekleri çeşitli işlemlerden sonra suda demlenerek tüketilir. Her ülkenin kültürel damak alışkanlıklarına göre ortaya çıkardığı kendine özgü içecekleri olsa da, kahve bunlardan farklı olarak yeryüzündeki çoğu insanın hayatına girmeyi başarmıştır. Her toplum kendine göre anlamlar yüklemiştir kahveye; kendine göre kavurmuş,<span>&nbsp;</span></span><span class="s2" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin-block-start: 1.25rem; display: inline-block;">demlemiş</span><span class="s1" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin-block-start: 1.25rem; display: inline-block; margin-block-end: 0px !important;">ve 
                            sunmuştur. Ortaya çıktığı günden bu yana sayısız insanın geçim kaynağı olmuştur ve yetiştiği bölgenin ekonomisine yön vermiştir. Günümüzde ise değerini artırarak insanların beğenisini kazanmaya ve dünyanın her köşesine durmaksınız ulaşmaya devam ediyor. Bu yüzden de dünya üzerinde petrolden sonra en çok ticareti yapılan madde olma özelliğini hala koruyor.</span></p>
                        <p class="p1" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin: 0px; margin-block-start: 0px !important;">
                            &nbsp;</p>
                        <h1 style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; font-size: var(--text-h1); line-height: 1.3; margin: 0px; margin-block-start: 1.25rem; font-family: var(--heading-font-family); font-weight: var(--heading-font-weight); font-style: normal; letter-spacing: normal; text-transform: var(--heading-text-transform); overflow-wrap: anywhere; color: rgb(17, 17, 17); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="s1" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin-block: 0px !important;">
                            <b style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; font-weight: bolder; margin-block: 0px !important;">KAHVENİN TARİHİ</b></span></h1>
                        <h2 class="p3" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; font-size: var(--text-h2); line-height: 1.4; margin: 0px; margin-block-start: 1.25rem; font-family: var(--heading-font-family); font-weight: var(--heading-font-weight); font-style: normal; letter-spacing: normal; text-transform: var(--heading-text-transform); overflow-wrap: anywhere; color: rgb(17, 17, 17); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: center;">
                            <img alt="mona lisa kahve içiyor" height="386" src="https://cdn.shopify.com/s/files/1/2714/0802/files/taft_coffee_kahve_nedir_kahve_tarihi_large.jpg?v=1566233495" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; vertical-align: middle; display: inline-block; color: rgba(0, 0, 0, 0); max-width: 100%; height: auto; margin-block: 0px !important; float: none;" width="386" /></h2>
                        <h2 class="auto-style3" style="box-sizing: border-box; border-style: solid; border-width: 0px; -webkit-font-smoothing: antialiased; font-size: var(--text-h2); line-height: 1.4; margin-block-start: 1.25rem; font-family: var(--heading-font-family); font-weight: var(--heading-font-weight); font-style: normal; letter-spacing: normal; text-transform: var(--heading-text-transform); overflow-wrap: anywhere; color: rgb(17, 17, 17); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-right: 0px; margin-top: 0px; margin-bottom: 0px;">&nbsp;</h2>
                        <h2 class="auto-style3" style="box-sizing: border-box; border-style: solid; border-width: 0px; -webkit-font-smoothing: antialiased; font-size: var(--text-h2); line-height: 1.4; margin-block-start: 1.25rem; font-family: var(--heading-font-family); font-weight: var(--heading-font-weight); font-style: normal; letter-spacing: normal; text-transform: var(--heading-text-transform); overflow-wrap: anywhere; color: rgb(17, 17, 17); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin-right: 0px; margin-top: 0px; margin-bottom: 0px;">
                            <span class="s1" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin-block: 0px !important;"><b style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; font-weight: bolder; margin-block: 0px !important;">KAHVE NASIL KEŞFEDİLDİ?</b></span></h2>
                        <p class="p3" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin: 0px; margin-block-start: 1.25rem; color: rgb(17, 17, 17); font-family: &quot;Nunito Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            <span class="s1" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin-block: 0px !important;">Kahve, dünya üzerinde en çok tüketilen içeceklerden biri olsa da ilk olarak ne zaman ortaya çıktığı konusunda kanıtlanmış bir bilgi yok. Bu durum, kahvenin keşfi hakkında birbirinden bağımsız pek çok rivayetin ortaya atılmasına sebep oluyor.</span></p>
                        <p class="p3" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin: 0px; margin-block-start: 1.25rem; color: rgb(17, 17, 17); font-family: &quot;Nunito Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            <span class="s1" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin-block: 0px !important;">Durum böyleyken kesin ifadelerle kahvenin keşfini anlatmamız mümkün değil, fakat en çok dillendirilmiş ve ortak noktaları bulunan efsaneler üzerinden kahvenin bulunuşu hakkında fikir sahibi olabiliyoruz.</span></p>
                        <p class="p3" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin: 0px; margin-block-start: 1.25rem; color: rgb(17, 17, 17); font-family: &quot;Nunito Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: center;">
                            <img alt="etiyopya haritası üzerinde kahve çekirdekleri" src="https://cdn.shopify.com/s/files/1/2714/0802/files/taft_coffee_kahve_nedir_kahve_nasil_bulundu_large.jpg?v=1566233715" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; vertical-align: middle; display: inline-block; color: rgba(0, 0, 0, 0); max-width: 100%; height: auto; margin-block: 0px !important; float: none;" /></p>
                        <p class="p3" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin: 0px; margin-block-start: 1.25rem; color: rgb(17, 17, 17); font-family: &quot;Nunito Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            <span class="s1" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin-block: 0px !important;">Bahsettiğimiz bu hikayelerin en meşhuru ise kahvenin Etiyopya’da keçiler sayesinde bulunduğunu anlatır. Bu rivayette dönemin Habeşistan sınırları içerisinde, günümüzde ise Etiyopya’ya bağlı olan bir bölgede çobanlık yapan Araplar, keçilerin günlerce uyumadığını ve enerji dolu olduklarını gözlemlemişler. Daha sonra bunun sebebini öğrenmek için keçilerin yaptıklarını incelediklerinde, keçilerin; daha önce görülmemiş bir bitkiyi yediklerini ve meydana gelen duruma bu bitkilerin sebep olduğunu düşünmüşler. Daha sonra bu bitkiyi toplayarak akıl danışmak için dervişlerine götürmüşler ve Şazili isimli bir derviş, aynı etkileri kendi üzerinde de görünce kahvenin ve kafeinin sihirli etkileri insanoğlu tarafından ilk kez anlaşılmış. İlk önce un haline getirilip ekmek hamuruna karıştırılarak tüketilen 
                            kahve çekirdeği, daha sonra suda kaynatılarak içilmiş ve günümüze kadar uzanan kahve serüveni de böylece başlamıştır.</span>&nbsp;</p>
                        <h2 style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; font-size: var(--text-h2); line-height: 1.4; margin: 0px; margin-block-start: 1.25rem; font-family: var(--heading-font-family); font-weight: var(--heading-font-weight); font-style: normal; letter-spacing: normal; text-transform: var(--heading-text-transform); overflow-wrap: anywhere; color: rgb(17, 17, 17); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">&nbsp;</h2>
                        <h2 style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; font-size: var(--text-h2); line-height: 1.4; margin: 0px; margin-block-start: 1.25rem; font-family: var(--heading-font-family); font-weight: var(--heading-font-weight); font-style: normal; letter-spacing: normal; text-transform: var(--heading-text-transform); overflow-wrap: anywhere; color: rgb(17, 17, 17); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="s1" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin-block: 0px !important;">
                            <b style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; font-weight: bolder; margin-block: 0px !important;">KAHVE DÜNYAYA NASIL YAYILDI?</b></span></h2>
                        <p class="p3" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin: 0px; margin-block-start: 1.25rem; color: rgb(17, 17, 17); font-family: &quot;Nunito Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: center;">
                            <img alt="kahve çuvalları" src="https://cdn.shopify.com/s/files/1/2714/0802/files/taft_coffee_kahve_nedir_kahve_dunyaya_nasil_yayildi_large.jpg?v=1566233961" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; vertical-align: middle; display: inline-block; color: rgba(0, 0, 0, 0); max-width: 100%; height: auto; margin-block: 0px !important; float: none;" /></p>
                        <p class="p3" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin: 0px; margin-block-start: 1.25rem; color: rgb(17, 17, 17); font-family: &quot;Nunito Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            <span class="s1" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin-block: 0px !important;">Kahve ilk kez Habeşistan’da tüketildikten sonra Yemen’e getirilmiştir ve asıl şöhretini burada kazanmıştır. Günümüzde Yemen, kahve denildiğinde akla gelen ilk ülkedir fakat kahvenin asıl vatanı burası değildir. Yemen, kahve kültürünü oluşturan ülkedir.</span></p>
                        <p class="p4" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin: 0px; margin-block-start: 1.25rem; color: rgb(17, 17, 17); font-family: &quot;Nunito Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            Kahvenin Habeşistan’dan dünyaya yayılmasını sağlayan kişinin ise Osmanlı Subayı Özdemir Paşa olduğu söylenir. Türk kahvesini diğer kahve kültürleriyle dönemsel olarak karşılaştırıldığında diğerlerine nazaran en eski tarihlere uzanması, bu iddianın doğru olduğunu kanıtlamaya yetiyor.</p>
                        <h3 style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; font-size: var(--text-h3); line-height: 1.5; margin: 0px; margin-block-start: 1.25rem; font-family: var(--heading-font-family); font-weight: var(--heading-font-weight); font-style: normal; letter-spacing: normal; text-transform: var(--heading-text-transform); overflow-wrap: anywhere; color: rgb(17, 17, 17); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">&nbsp;</h3>
                        <h3 style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; font-size: var(--text-h3); line-height: 1.5; margin: 0px; margin-block-start: 1.25rem; font-family: var(--heading-font-family); font-weight: var(--heading-font-weight); font-style: normal; letter-spacing: normal; text-transform: var(--heading-text-transform); overflow-wrap: anywhere; color: rgb(17, 17, 17); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="s1" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin-block: 0px !important;">
                            <b style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; font-weight: bolder; margin-block: 0px !important;">KAHVE İSMİNİ NEREDEN ALIYOR?</b></span></h3>
                        <p class="p4" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin: 0px; margin-block-start: 1.25rem; color: rgb(17, 17, 17); font-family: &quot;Nunito Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            Habeşistan’da kahve yetişen bir bölge olan Kaffa’nın, kahveye ismini verdiği söylenir. İki kelime arasındaki benzerlik ve kahvenin Habeşistan’da keşfedildiği iddiası, bu görüşü destekliyor.&nbsp;&nbsp;</p>
                        <h1 class="p5" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; font-size: var(--text-h1); line-height: 1.3; margin: 0px; margin-block-start: 1.25rem; font-family: var(--heading-font-family); font-weight: var(--heading-font-weight); font-style: normal; letter-spacing: normal; text-transform: var(--heading-text-transform); overflow-wrap: anywhere; color: rgb(17, 17, 17); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">&nbsp;</h1>
                        <h1 class="p5" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; font-size: var(--text-h1); line-height: 1.3; margin: 0px; margin-block-start: 1.25rem; font-family: var(--heading-font-family); font-weight: var(--heading-font-weight); font-style: normal; letter-spacing: normal; text-transform: var(--heading-text-transform); overflow-wrap: anywhere; color: rgb(17, 17, 17); font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="s1" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin-block: 0px !important;">
                            <b style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; font-weight: bolder; margin-block: 0px !important;">DÜNYA ÜZERİNDEKİ KAHVE KÜLTÜRLERİ</b></span></h1>
                        <p class="p3" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin: 0px; margin-block-start: 1.25rem; color: rgb(17, 17, 17); font-family: &quot;Nunito Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            <span class="s1" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin-block: 0px !important;">Her millet, kendi kültürünün mirası olan damak tadı ve yaşadığı iklimin sahip olduğu özellikler sonucunda kahveyi farklı şekillerde tüketmiştir. Bu farklar kahvenin pişirilme şeklinde ve lezzetlendirmek için yapılan ilave malzemelerde ayrışmaya sebep olmuştur. Her millet kendi kahve kültürünü yaşatmaya devam ediyor fakat birçoğu küresel boyutta diğer ülkeleri etkileyememiş, bazıları ise kendi kültürünü tüm dünyaya benimsetmiş durumda.</span></p>
                        <p class="p3" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin: 0px; margin-block-start: 1.25rem; color: rgb(17, 17, 17); font-family: &quot;Nunito Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            &nbsp;</p>
                        <p class="auto-style4" style="box-sizing: border-box; border-style: solid; border-width: 0px; -webkit-font-smoothing: antialiased; margin: 0px; margin-block-start: 1.25rem; color: rgb(17, 17, 17); font-family: &quot;Nunito Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            <strong>HAKKIMIZDA/İLETİŞİM</strong></p>
                        <p class="auto-style4" style="box-sizing: border-box; border-style: solid; border-width: 0px; -webkit-font-smoothing: antialiased; margin: 0px; margin-block-start: 1.25rem; color: rgb(17, 17, 17); font-family: &quot;Nunito Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            -Kubilay Topaktaş-&nbsp;&nbsp; </p>
                        <p class="auto-style4" style="box-sizing: border-box; border-style: solid; border-width: 0px; -webkit-font-smoothing: antialiased; margin: 0px; margin-block-start: 1.25rem; color: rgb(17, 17, 17); font-family: &quot;Nunito Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            kubilaytopaktas@hotmail.com</p>
                        <p class="p3" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin: 0px; margin-block-start: 1.25rem; color: rgb(17, 17, 17); font-family: &quot;Nunito Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 239, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                            &nbsp;</p>
                        <p class="p1" style="box-sizing: border-box; border-style: solid; border-width: 0px; border-color: rgb(var(--border-color)); -webkit-font-smoothing: antialiased; margin: 0px; margin-block-start: 0px !important;">
                            &nbsp;</p>
                    </div>
                </div>
            </div>
        </div>
    </form>
</body>
</html>
